name: Spellcheck

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Spellcheck with Hunspell
      run: |
        sudo apt-get install -y hunspell
        chmod +x spellcheck.sh
        ./spellcheck.sh